# Generated by Django 6.0.2 on 2026-02-17 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, unique=True)),
                ('clase', models.CharField(choices=[('Industrial', 'Industrial'), ('Comercial', 'Comercial'), ('Residencial', 'Residencial')], default='Residencial', max_length=20)),
                ('nombre', models.CharField(max_length=300)),
                ('tipologia', models.CharField(blank=True, default='', max_length=200)),
                ('operacion', models.CharField(choices=[('Venta', 'Venta'), ('Alquiler', 'Alquiler')], default='Venta', max_length=20)),
                ('link_maps', models.URLField(blank=True, default='', max_length=500)),
                ('distrito', models.CharField(blank=True, default='', max_length=200)),
                ('pitch', models.TextField(blank=True, default='')),
                ('calle', models.CharField(blank=True, default='', max_length=300)),
                ('direccion', models.CharField(blank=True, default='', max_length=500)),
                ('referencia', models.TextField(blank=True, default='')),
                ('antiguedad', models.CharField(blank=True, default='', max_length=100)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('costo_mantenimiento', models.CharField(blank=True, default='', max_length=200)),
                ('metraje', models.CharField(blank=True, default='', max_length=100)),
                ('vista', models.CharField(blank=True, default='', max_length=200)),
                ('distribucion', models.TextField(blank=True, default='')),
                ('ascensor', models.CharField(blank=True, default='', max_length=100)),
                ('habitaciones', models.CharField(blank=True, default='', max_length=100)),
                ('cocheras', models.CharField(blank=True, default='', max_length=100)),
                ('cantidad_pisos', models.CharField(blank=True, default='', max_length=100)),
                ('tipo_cocina', models.CharField(blank=True, default='', max_length=200)),
                ('terraza_balcon', models.CharField(blank=True, default='', max_length=200)),
                ('piso', models.CharField(blank=True, default='', max_length=100)),
                ('banos', models.CharField(blank=True, default='', max_length=100)),
                ('cuarto_servicio', models.CharField(blank=True, default='', max_length=100)),
                ('bano_servicio', models.CharField(blank=True, default='', max_length=100)),
                ('documentacion', models.TextField(blank=True, default='')),
                ('parametros_usos', models.TextField(blank=True, default='')),
                ('financiamiento', models.TextField(blank=True, default='')),
                ('imagen_1', models.URLField(blank=True, default='', max_length=500)),
                ('imagen_2', models.URLField(blank=True, default='', max_length=500)),
                ('imagen_3', models.URLField(blank=True, default='', max_length=500)),
                ('imagen_4', models.URLField(blank=True, default='', max_length=500)),
                ('imagen_5', models.URLField(blank=True, default='', max_length=500)),
                ('video', models.URLField(blank=True, default='', max_length=500)),
                ('recorrido_360', models.URLField(blank=True, default='', max_length=500)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.agent')),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
