# Generated by Django 6.0.2 on 2026-02-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='metraje',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='property',
            name='recorrido_360',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
