# Generated by Django 6.0.2 on 2026-02-17 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_metraje_alter_property_recorrido_360'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='google_access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agent',
            name='google_calendar_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='google_refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agent',
            name='google_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_phone', models.CharField(blank=True, default='', max_length=50)),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField()),
                ('google_event_id', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('cancelled', 'Cancelada'), ('completed', 'Completada')], default='scheduled', max_length=20)),
                ('conversation_session_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='properties.agent')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='properties.property')),
            ],
            options={
                'ordering': ['-datetime_start'],
            },
        ),
    ]
