# Generated by Django 5.2 on 2026-02-17 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_agent_google_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='imagen_1',
        ),
        migrations.RemoveField(
            model_name='property',
            name='imagen_2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='imagen_3',
        ),
        migrations.RemoveField(
            model_name='property',
            name='imagen_4',
        ),
        migrations.RemoveField(
            model_name='property',
            name='imagen_5',
        ),
        migrations.RemoveField(
            model_name='property',
            name='video',
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='properties/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='properties.property')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
