# Generated by Django 5.2 on 2026-02-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_property_imagen_1_remove_property_imagen_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
