# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propertyimage_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='tipologia',
            field=models.CharField(blank=True, choices=[('Casa', 'Casa'), ('Casa de playa', 'Casa de playa'), ('Casa de campo', 'Casa de campo'), ('Departamento', 'Departamento'), ('Terreno', 'Terreno')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólares'), ('PEN', 'Soles')], default='USD', max_length=3),
        ),
    ]
