# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_tipologia_choices_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='tipologia',
            field=models.CharField(blank=True, choices=[('Casa', 'Casa'), ('Casa de playa', 'Casa de playa'), ('Casa de campo', 'Casa de campo'), ('Departamento', 'Departamento'), ('Dúplex', 'Dúplex'), ('Triplex', 'Triplex'), ('Terreno', 'Terreno'), ('Local industrial', 'Local industrial'), ('Local comercial', 'Local comercial')], default='', max_length=200),
        ),
    ]
