# Generated by Django 6.0.2 on 2026-02-17 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chatconversation_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('operacion', models.CharField(blank=True, default='', max_length=50)),
                ('tipo_propiedad', models.CharField(blank=True, default='', max_length=100)),
                ('distritos', models.CharField(blank=True, default='', max_length=500)),
                ('precio_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('habitaciones', models.CharField(blank=True, default='', max_length=50)),
                ('caracteristicas', models.TextField(blank=True, default='')),
                ('resumen', models.TextField(blank=True, default='')),
                ('notificado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='chatbot.chatconversation')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
