# Generated by Django 6.0.2 on 2026-04-19 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_chatconversation_first_property'),
        ('properties', '0010_prohibicion_property_prohibiciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_shown_at', models.DateTimeField(auto_now_add=True)),
                ('last_shown_at', models.DateTimeField(auto_now=True)),
                ('shown_count', models.PositiveIntegerField(default=1)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_properties', to='chatbot.chatconversation')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_interests', to='properties.property')),
            ],
            options={
                'ordering': ['-last_shown_at'],
                'unique_together': {('conversation', 'property')},
            },
        ),
    ]
